log:
  console: true
  file: logs/bot.log
  level: INFO
  max_size: 10 MB
  retention: 7 days
  rotation: 1 day
onebot:
  access_token: null
  heartbeat_interval: 5000
  host: 127.0.0.1
  path: /
  port: 8029
  reconnect_interval: 5000
  retry_count: 3
  retry_interval: 5
  secret: null
  timeout: 30
onebot_engine:
  config_path: engine/appsettings.json
  login_timeout: 60
  working_dir: engine
server:
  debug: false
  host: 127.0.0.1
  port: 8080
  workers: 1
storage:
  auto_backup: true
  backup_interval: 24
  data_dir: data
  type: json
wordlib:
  auto_reload: true
  cache_size: 1000
  case_sensitive: false
  default_match_type: exact
  enable_pseudocode: true
  encoding: utf-8
  json_storage_path: data/wordlib.json
  max_reply_length: 1000
  path: data/wordlib
